server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pros?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ljh.firsts.model
http:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true